### PR TITLE
Fix docs for `SlidingAverage.clear`

### LINKED ISSUE #594: SlidingAverage.clear() does not reset average to initial state
@gavin-norman-sociomantic : 

The method's documentation states:

```
Resets the average counter to its initial state.
```

However, the initial state of the `_average` member is NaN, not 0.

### PR DESCRIPTION
**Pull request by mihails-strasuns**
Fixes #594

### CODE REVIEW

**Review by gavin-norman-sociomantic — APPROVED** [review]

File: src/ocean/math/SlidingAverage.d [hunk 1]
```diff
@@ -178,18 +178,21 @@ public class SlidingAverage ( T )
 
     /***************************************************************************
 
-        Resets the average counter to its initial state.
+        Resets the average counter to the zerol state:
```
Comment (gavin-norman-sociomantic) [inline src/ocean/math/SlidingAverage.d]: Oh wait, typo: "zerol".

**Comment by mihails-strasuns** [comment]
Update

**Review by gavin-norman-sociomantic — APPROVED** [review]
