### PR TITLE
Handle nested Contiguous fields in deserializer

### LINKED ISSUE #87: Serializer must process `Contiguous!(S)` fields as structs
Currently this test fails with contiguity contract violated:

```D

unittest
{
    static struct Inner { mstring s; }
    static struct Outer { Contiguous!(Inner) inner; }

    auto s1 = Inner("abcd".dup);
    Outer s2;
    copy(s1, s2.inner);

    Contiguous!(Outer) s3; // nested contiguous struct
    copy(s2, s3);
    s3.ptr.inner.enforceIntegrity(); // fails
}
```

```
./src/ocean/util/serialize/contiguous/Contiguous.d:203: unexpected exception object.Exception: expression '0X00007F76C4F08FB8 >= 0X00007F76C4F214D8' evaluates to false
```

Problem happens because `Contiguous` struct is simply a wrapper on top of `void[]` from the PoV of the type system. As such, it will be serialized same as plain `void[]` array, as a raw sequence of bytes - meaning any internal pointers it contains won't be updated to refer to new buffer.

The only possible fix is to add special support of `Contiguous` structs to serializer itself, processing them as struct type instead.

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
Fixed #87

### CODE REVIEW

File: src/ocean/util/serialize/contiguous/Deserializer.d [hunk 1]
```diff
@@ -872,7 +872,22 @@ struct Deserializer
...
+                    auto pfield = This.getField!(i, Field)(s);
+                    auto increment = This.sliceArray(*pfield, data[pos .. $],
+                        slices_buffer);
+
+                    // if host struct is Contiguous, internal `data` array
+                    // needs to be deserialized as a struct to ensure that
+                    // internal pointers are updated and it stays contiguous
+                    static if (is(S T == Contiguous!(T)))
+                    {
+                        static assert (is(typeof(*pfield) == void[]));
```
Comment (david-eckardt-sociomantic) [inline src/ocean/util/serialize/contiguous/Deserializer.d]: Or `is(Element == void)`, a bit shorter.

File: src/ocean/util/serialize/contiguous/Deserializer.d [hunk 2]
```diff
@@ -872,7 +872,22 @@ struct Deserializer
...
+                        auto orig_length = pfield.length;
+                        deserialize!(T)(*pfield);
+                        assert (orig_length == pfield.length);
```
Comment (david-eckardt-sociomantic) [inline src/ocean/util/serialize/contiguous/Deserializer.d]: Could this even be
```d
auto orig_field = *pfield;
deserialize!(T)(*pfield);
assert (orig_field is *pfield);
```
i.e. `field` is not even relocated?

Comment (mihails-strasuns-sociomantic) [reply src/ocean/util/serialize/contiguous/Deserializer.d]: I wanted to safeguard against case when it may shrink it without relocating

File: src/ocean/util/serialize/contiguous/Deserializer.d (hunk 1 above)
Comment (mihails-strasuns-sociomantic) [reply src/ocean/util/serialize/contiguous/Deserializer.d]: :+1:

Comment (mihails-strasuns-sociomantic) [reply src/ocean/util/serialize/contiguous/Deserializer.d]: Updated, also added release notes

**Comment by mihails-strasuns-sociomantic** [comment]
Ping @david-eckardt-sociomantic

**Comment by david-eckardt-sociomantic** [comment]
Hm, the `static assert(is(Element == void))` seems to be gone now. Do you think it isn't necessary?

**Comment by mihails-strasuns-sociomantic** [comment]
Line 884? `static assert (is(Element == void));`

**Comment by david-eckardt-sociomantic** [comment]
Sorry, I was blind.

File: relnotes/nested-ctg.feature.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+* `ocean.util.serializer.contiguous.Deserializer`
+
+  It is now possible to (de)serialize structs containing `Contgiguous` structs
```
Comment (david-eckardt-sociomantic) [inline relnotes/nested-ctg.feature.md]: typo `Cont_g_iguous`

Comment (mihails-strasuns-sociomantic) [reply relnotes/nested-ctg.feature.md]: Fixed

**Review by david-eckardt-sociomantic — APPROVED** [review]

**Comment by david-eckardt-sociomantic** [comment]
Needs rebasing.

**Comment by mihails-strasuns-sociomantic** [comment]
Rebased
