### PR TITLE
Use custom exception type for out of bound in Stack

### LINKED ISSUE #297: Fix JsonParser throwing inconsistent exceptions or errors
Depending on the D version used, JsonParser will throw a different exception or error. In order to make it consistent it should throw always a `JsonParserException` so a program using the module can catch the exception whatever is the D version currently in use.
 
```D
unittest
{
    static immutable istring json =
    `{
        "products": {
        }}
    }`;

    auto p = new JsonParser!(char)(json);
    assert(p);
    assert(p.type == p.Token.BeginObject);
    assert(p.next);
    assert(p.type == p.Token.Name);
    assert(p.value == "products", p.value);
    assert(p.next);
    assert(p.value == "", p.value);
    assert(p.next);
    assert(p.type == p.Token.EndObject);
    assert(p.next);
    assert(p.type == p.Token.EndObject);

    try
    {
        assert(p.next);
    }
    catch (Exception e)
    {
        // catch in D1
    }
    catch
    {
        // catch in D2
    }
}
```

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
Fixes #297

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
I'm scared to say anything about breaking the code cause the different exception is now thrown on this one :no_mouth:

File: src/ocean/util/container/more/Stack.d [hunk 1]
```diff
@@ -133,7 +133,7 @@ struct Stack (V, int Size = 0)
                           if (depth < stack.length)
```
Comment (nemanja-boric-sociomantic) [inline src/ocean/util/container/more/Stack.d:135]: These all `if (...)` can be converted to enforce for a nicer code.

**Comment by mihails-strasuns-sociomantic** [comment]
Oh, you mean our D1-only apps doing `catch (RangeException)` with previous code?

File: src/ocean/util/container/more/Stack.d (hunk 1 above)
Comment (mihails-strasuns-sociomantic) [reply src/ocean/util/container/more/Stack.d:135]: Full rewrite of module code style is my next step :)

**Comment by nemanja-boric-sociomantic** [comment]
Yeah.

**Comment by mihails-strasuns-sociomantic** [comment]
This is actually both totally legit and damn scary concern :/

**Comment by nemanja-boric-sociomantic** [comment]
I wonder if we can keep throwing `ArrayBoundsException` (`StackException: ArrayBoundsException`) in D1 and in D2 do `StackException: Exception`. Given that the users couldn't (yeah, right) catch `RangeError` in the past, we could get away with this approach.

**Comment by mihails-strasuns-sociomantic** [comment]
Sounds on the edge of acceptable :)

**Comment by nemanja-boric-sociomantic** [comment]
What's happening with the codecov? Is it not attached, is it #298 a cause for it? I doubt it, but IIRC we had some issues with it in #230, that's why it got too complicated and forgotten in the end.

**Comment by nemanja-boric-sociomantic** [comment]
It looks like it's just not reported to the PR: https://codecov.io/github/sociomantic-tsunami/ocean/commit/77b6c23bc60e9b3c23dafe5c68a48989e8bb2c8e

**Comment by mihails-strasuns-sociomantic** [comment]
Not entirely sure. If I go their website and open ocean PR list in the reports, I can find it there (and log shows it gets submitted without problems). But it doesn't set any status.

**Comment by mihails-strasuns-sociomantic** [comment]
Updated with coding style and tests

**Comment by mihails-strasuns-sociomantic** [comment]
Updated: fix another undefined behaviour bug found by added tests :)

File: src/ocean/util/container/more/Stack.d [hunk 2]
```diff
@@ -311,6 +306,48 @@ struct Stack (V, int Size = 0)
...
+    this ( )
+    {
+        version (D_Version2)
+            super("Out of bounds access attempt to stack struct");
+        else
+            super("", 0);
+    }
+}
+
+// HACK: some D1 code may be trying to catch ArrayBoundsException specifically
```
Comment (gavin-norman-sociomantic) [inline src/ocean/util/container/more/Stack.d:413]: Would be worth mentioning what the plan is for removing this hack.

File: src/ocean/util/container/more/Stack.d [hunk 3]
```diff
@@ -311,6 +306,48 @@ struct Stack (V, int Size = 0)
...
+{
+    Stack!(int) stack;
+    stack.push(42);
+    test!("==")(stack.pop(), 42);
+    testThrown!(StackBoundsException)(stack.pop());
+}
+
+/*******************************************************************************
+
+    Exception used instead of uncatchable `RangeError`.
```
Comment (gavin-norman-sociomantic) [inline src/ocean/util/container/more/Stack.d]: This comment only seems relevant from the perspective of this moment in time (i.e. this commit). It doesn't seem relevant doc for this module, in general.

File: src/ocean/util/container/more/Stack.d [hunk 4]
```diff
@@ -284,17 +290,6 @@ struct Stack (V, int Size = 0)
                 return stack [0 .. depth];
         }
 
-        /**********************************************************************
-
-                Throw an exception
-
-        **********************************************************************/
-
-        private V error (size_t line)
```
Comment (gavin-norman-sociomantic) [inline src/ocean/util/container/more/Stack.d:293]: What? Good riddance.

File: src/ocean/util/container/more/Stack.d [hunk 5]
```diff
@@ -203,7 +207,8 @@ struct Stack (V, int Size = 0)
                    return p[1] = v;
                    }
 
-                return error (__LINE__);
```
Comment (gavin-norman-sociomantic) [inline src/ocean/util/container/more/Stack.d:206]: `return`? This code was super weird!

File: src/ocean/util/container/more/Stack.d [hunk 6]
```diff
@@ -1,309 +1,316 @@
 /*******************************************************************************
```
Comment (gavin-norman-sociomantic) [inline src/ocean/util/container/more/Stack.d:1]: >Fix Stack coding style and cover it with tests

In a patch release?

File: src/ocean/util/container/more/Stack.d [hunk 7]
```diff
@@ -351,43 +429,43 @@ static this ( )
 
 /*******************************************************************************
 
-*******************************************************************************/
+ *******************************************************************************/
 
 debug (Stack)
```
Comment (mathias-lang-sociomantic) [inline src/ocean/util/container/more/Stack.d]: Remove ?

Comment (mihails-strasuns-sociomantic) [reply src/ocean/util/container/more/Stack.d]: Already removed in 3.5.x, don't want conflicts

File: src/ocean/util/container/more/Stack.d (hunk 6 above)
Comment (mihails-strasuns-sociomantic) [reply src/ocean/util/container/more/Stack.d:1]: This module had exactly 0 tests so I had to do something to actually check that things work. Now that they do, we could possibly move all the part adding tests & style to minor but it would be a bit scary to merge fix without tests coming in a pair.

Comment (gavin-norman-sociomantic) [reply src/ocean/util/container/more/Stack.d:1]: The massive coding style changes are more what I was referring to.

File: src/ocean/util/container/more/Stack.d (hunk 2 above)
Comment (mihails-strasuns-sociomantic) [reply src/ocean/util/container/more/Stack.d:413]: On this topic - any idea how we could possibly handle it? I can only think of deprecating `ArrayBoundsException` alias in `ocean.core` to ensure no one refers to it directly.

File: src/ocean/util/container/more/Stack.d (hunk 7 above)
Comment (mathias-lang-sociomantic) [reply src/ocean/util/container/more/Stack.d]: But you changed the indent, so you'll get them anyway

File: src/ocean/util/container/more/Stack.d (hunk 2 above)
Comment (nemanja-boric-sociomantic) [reply src/ocean/util/container/more/Stack.d:413]: I think that's fair enough.

**Comment by mihails-strasuns-sociomantic** [comment]
Modified PR to only contains fixes and added tests. Will make another one against v3.x.x after point release with the rest.

**Comment by mihails-strasuns-sociomantic** [comment]
Pushed one more UB fix. This module is about to overload my crap detector.

**Comment by mihails-strasuns-sociomantic** [comment]
Green

**Review by nemanja-boric-sociomantic — APPROVED** [review]
