### PR TITLE
Resolve infinite loop on a Cache clear

### LINKED ISSUE #679: Infinite loop on ICache.clear and corrupted state
ICache.clear produce an infinite loop in some situations.

ICache is a base class for a bunch of different caches.
ICache has 2 containers inside TimeToIndex and KeyToNode. 
KeyToNode is HashMap of TimeToIndex.Node* with custom allocator.
The HashMap use liked lists in each Bucket. 
Loops in Bucket's liked lists cause infinite traverse time of that lists.

Except for infinite loop on clear this bug could be a cause of a corrupted state of the hash map. 
When we have the same linked list node several times in one or many linked lists then we lose data on each hashmap write operation. The allocator can return pointer on linked list node which isn't free and contains some data. When we put new data in this node we erase data which was there before. 
The allocator can return pointer on some node several times and as a result, this node could be present several times in some list or even several times in different linked lists.

Here's a unit test to reproduce this issue

```
unittest
{
    KeyToNode am_related = new KeyToNode(100000);
    am_related.clear();
     am_related.put(9207674216414740734);
    am_related.put(8595442437537477107);
    am_related.clear();
    am_related.put(8595442437537477107);
    am_related.clear();
    am_related.put(9207674216414740734);
    am_related.put(8595442437537477106);
    am_related.put(8595442437537477108);
    am_related.put(8595442437537477110);
    am_related.put(8595442437537477112);
    am_related.clear();
    assert(false, "isn't reacheble");
}
```

### PR DESCRIPTION
**Pull request by Aleksandr-Mamonov-Dunnhumby**
BucketElementFreelist store free/dealocated Elements in a linked list.
on new item request it use item from linked list if it isn't empty.
if linked list is empty ArrayAllocatedFreeBucketElements ask
GenericArrayPool for a new item.

If ArrayAllocatedFreeBucketElements.clear calls GenericArrayPool.clear
then Pool marks all Elements as free. Meanwhile BucketList puts same
Elements in linked list. When BucketList will has use all Elements in a
linked list it will ask Pool for new items and a Pull will return just used
Elements (Elements which are using right now).

Without Pool.clear call Pool returns each Element once and then it reused
by BucketList.
Fix #679

### CODE REVIEW

File: src/ocean/util/container/map/model/BucketElementFreeList.d [hunk 1]
```diff
@@ -436,5 +266,186 @@ abstract class IBucketElementFreeList: IAllocator
...
+        Params:
+            predicate = delegate which define node searching criteria
+
+        Returns:
+            return first node match to predicate
+            either
+            return null if there is no node which match to predicate
+
+     **************************************************************************/
+    public ListNode* find( bool delegate(ListNode*) predicate)
```
Comment (stefan-koch-sociomantic) [inline src/ocean/util/container/map/model/BucketElementFreeList.d]: why do you need this.
Linked list search is freaking (if not pointing into a contiguous memory-block).
it should not expose a find primitive.

**Comment by stefan-koch-sociomantic** [comment]
at least find is private now, good.

**Comment by mihails-strasuns** [comment]
I am not very familiar with container code, would prefer @gavin-norman-sociomantic to have a look.

**Comment by matthias-wende-sociomantic** [comment]
I had a first quick look. Can you please explain in more detail why it is necessary to change `BucketElementFreeList` and the relation to this bugix.

I also wonder if removing the `IBucketElementFreeList` interface is really necessary in this PR, not that I'm against it, but less changes would make it simpler to review.

**Review by matthias-wende-sociomantic — APPROVED** [review]
Approved! It makes sense after the explanation you gave to me. Still I would wait until @gavin-norman-sociomantic gives his final approval.

File: src/ocean/util/container/cache/model/containers/KeyToNode.d [hunk 2]
```diff
@@ -85,22 +85,37 @@ class KeyToNode: HashMap!(TimeToIndex.Node*)
 
     public this ( size_t n )
     {
-        super(this.allocator = new ArrayAllocatedFreeBucketElements(n), n);
+        this.allocator = new ArrayAllocatedFreeBucketElements(n);
+        super(this.allocator, n);
```
Comment (don-clugston-sociomantic) [inline src/ocean/util/container/cache/model/containers/KeyToNode.d:91]: This seems to be a refactoring, nothing to do with the fix.

**Comment by don-clugston-sociomantic** [comment]
This was a bit hard to understand.

From looking at this code, the bug appears to be visible from the doc comments at the start of the module:
` Limits the number of available mappings to a fixed value and preallocates all bucket elements in an array buffer.`

When the container is cleared, the bucket elements should remain preallocated. So it shouldn't clear them.

I suggest changing the doc comments for the allocator member to be something like:
`
        Bucket elements allocator.
        The elements are allocated only during container construction, and never freed.
`

File: src/ocean/util/container/cache/model/containers/KeyToNode.d (hunk 2 above)
Comment (Aleksandr-Mamonov-Dunnhumby) [reply src/ocean/util/container/cache/model/containers/KeyToNode.d:91]: yes, it's a refactoring

**Comment by matthias-wende-sociomantic** [comment]
Agreed, this is hard to understand. I checked again with @Aleksandr-Mamonov-Dunnhumby and now feel confident to merge. Thanks everyone!

**Comment by don-clugston-sociomantic** [comment]
LGTM
