### PR TITLE
Move the SmartUnion's active member enforcement into method body

### LINKED ISSUE #96: Ocean must pass tests when run with `-release`
Essentially another form of the goal to clean up `assert` usage in ocean to make `-release` flag feasible for our applications. Right now it doesn't even pass tests because some failed assertions are checked with `testThrown`.

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**
The enforcement which was used to confirm that the active member
has been accessed was omitted in the `-release` build. Now it's moved
in the method's body and it still active, no matter if compiled with
`-release`.

Fixes #96

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
`enforce` or `verify`? Is the intent of smart union that one shall never call `get` with wrong type?

**Comment by nemanja-boric-sociomantic** [comment]
I think so, I'll use verify.

**Comment by nemanja-boric-sociomantic** [comment]
Updated. I've also added the matrix item with `-release`, let's see if that work.

**Comment by nemanja-boric-sociomantic** [comment]
Ok, passing `DFLAGS=-release` to travis works:

https://travis-ci.org/sociomantic-tsunami/ocean/jobs/272091389

File: src/ocean/core/SmartUnion.d [hunk 1]
```diff
@@ -503,9 +503,9 @@ private template Methods ( U, uint i )
     const type = "typeof(" ~ member_access ~ ")";
 
     const get = type ~ ' ' ~  member ~ "() "
-        ~ "in { enforce(_.active == _.active." ~ member ~ ", "
```
Comment (gavin-norman-sociomantic) [inline src/ocean/core/SmartUnion.d:506]: Oof sneaky!

**Review by gavin-norman-sociomantic — APPROVED** [review]

**Review by mihails-strasuns-sociomantic — APPROVED** [review]
