### PR TITLE
Throw exception instead of error in ParamSet

### LINKED ISSUE #471: Remove catch of ArrayBoundsCheckException in QueryParams
https://github.com/sociomantic-tsunami/ocean/blob/fb5f7928e46e3d75c2a251f0dc54c901e3392f9d/src/ocean/net/util/ParamSet.d#L152-L163

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
Fixes #471

### CODE REVIEW

**Review by gavin-norman-sociomantic — APPROVED** [review]
Makes sense to me. Maybe someone in charge of the HTTP server code could double check.

**Comment by mihails-strasuns-sociomantic** [comment]
That would be @ben-palmer-sociomantic @andrew-stevenson-sociomantic ?

File: src/ocean/net/util/ParamSet.d [hunk 1]
```diff
@@ -151,15 +150,14 @@ class ParamSet
...
-        }
-        catch (ArrayBoundsException e)
-        {
-            e.msg ~= " [\"" ~ key ~ "\"]";
-            throw e;
-        }
+        key = this.tolower(key);
+        auto value = key in this.paramset;
+        verify(
+            value,
```
Comment (david-eckardt-sociomantic) [inline src/ocean/net/util/ParamSet.d]: `value !is null`

**Comment by david-eckardt-sociomantic** [comment]
@stefan-brus-sociomantic, too.

**Comment by ben-palmer-sociomantic** [comment]
So this will preserve the D1 behaviour right? I haven't started testing with D2 builds much yet.

**Comment by stefan-brus-sociomantic** [comment]
Same here. So `ArrayBoundsException` is an error, and not actually an exception?

also FYI @scott-gibson-sociomantic

**Comment by mihails-strasuns-sociomantic** [comment]
@ben-palmer-sociomantic it will preserve it in a sense that exception will be thrown in both debug and release builds and it can be caught. But exception type/name will be different.

**Comment by mihails-strasuns-sociomantic** [comment]
@stefan-brus-sociomantic yes https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/core/ExceptionDefinitions.d#L63-L68

I intend to deprecate them all in next ocean minor, as using those is not Ok for migration stages 3/4.

**Comment by david-eckardt-sociomantic** [comment]
> So `ArrayBoundsException` is an error, and not actually an exception?

Yes, it is actually [`RangeError`](https://dlang.org/phobos/core_exception.html#.RangeError).

**Comment by mihails-strasuns-sociomantic** [comment]
Good to merge?

**Comment by mihails-strasuns-sociomantic** [comment]
Ping

File: src/ocean/net/util/ParamSet.d [hunk 2]
```diff
@@ -151,15 +150,14 @@ class ParamSet
...
-        catch (ArrayBoundsException e)
-        {
-            e.msg ~= " [\"" ~ key ~ "\"]";
-            throw e;
-        }
+        key = this.tolower(key);
+        auto value = key in this.paramset;
+        verify(
+            value !is null,
+            format("Key '{}' is not found in ParamSet", key)
```
Comment (nemanja-boric-sociomantic) [inline src/ocean/net/util/ParamSet.d:157]: Unrelated to this PR, and it's probably not too important, but this allocates, while the `verify` uses reusable instance. Perhaps this could be misused, if the remote party attack us with the requests to hit this path. Is there any way that we format-enable the `Verify` so it can reuse the message buffer?

The answer is probably "no", since we tend not to import anything in `Verify` module.

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Comment by vasileios-kyrillidis-sociomantic** [comment]
Andrew is on vacation and back on Monday. I don't see this used by us to be honest (maybe I didn't check thoroughly enough) so I believe it should be fine.

File: src/ocean/net/util/ParamSet.d (hunk 2 above)
Comment (mihails-strasuns-sociomantic) [reply src/ocean/net/util/ParamSet.d:157]: So this is not under control of the app? If yes, I should replace `verify` here with custom exception type. `verify` is expected to never be hit in production, as it basically replaces `assert`.

Comment (nemanja-boric-sociomantic) [reply src/ocean/net/util/ParamSet.d:157]: That is a good point. Two applications that I've look into (search for the `QueryParams` and `QueryParamSet`) are fine with this being an assertion, not enforce, since they fill the `ParamSet` with the empty value for every key, then parse the query filling as much values as they can and then they lookup the keys that are guaranteed to be in the set.

Comment (david-eckardt-sociomantic) [reply src/ocean/net/util/ParamSet.d:157]: > So this is not under control of the app?

It is under control of the application. The application knows which keys are in the set. 
The method documentation says, "key must be one of the parameter keys passed on instantiation or added by a subclass." Like AA indexing the application should call this method only if it can for sure pass one of these as a parameter, otherwise it should use `opIn_r`.

**Review by david-eckardt-sociomantic — APPROVED** [review]
