### PR TITLE
Fix several Serializer and Deserializer bugs, especially const

### LINKED ISSUE #79: Deserializer trouble with const(T[])[] struct fields
`Deserializer` does not correctly deserialise `const(T[])[]` struct fields. The problem is a qualifier-incompatible way of checking for a dynamic array in [`sliceSubArrays`](https://github.com/sociomantic-tsunami/ocean/blob/v2.x.x/src/ocean/util/serialize/contiguous/Deserializer.d#L1050-L1052).
For the reference type qualifier inexperienced, this is how it fails:
```d
alias const(char[])[] T;
// Check if T is an array, and if so, derive the element type:
static if (is (T V : V[]))
{
    // V is const(char)
    // Now check if T is a dynamic array:
    static if (is(V[] == T)) // compares const(char)[] with const(char[]) -- not the same
    { /* ... */ }
    else
    { /* False negative, T is a dynamic array. */ }
}
```
So far so good, this can be fixed. But then another problem occurs: [`sliceSubArrays`](https://github.com/sociomantic-tsunami/ocean/blob/v2.x.x/src/ocean/util/serialize/contiguous/Deserializer.d#L1056) cannot call [`sliceArray`](https://github.com/sociomantic-tsunami/ocean/blob/v2.x.x/src/ocean/util/serialize/contiguous/Deserializer.d#L907) because the `out` parameter of `sliceArray` would need to be the array element type `const(char[])` -- which is illegal, an `out` parameter cannot be `const`.
This conflict is a symptom of a more fundamental problem with deserialising `const`. Given a struct
```d
struct S
{
    const(T[]) a;
}
```
What the deserialiser essentially does is the following:
```d
void[] input_data;
void[] slices_buf;
S dst;
dst.a = cast(const(T[]))(slices_buf[
    0 .. numberOfElements(input_data) * const(T[]).sizeof
]);
foreach (ref element; dst.a)
{
    element = deserialiseNextElement(data);
}
```
The problem here is that the assignment in the `foreach` loop is illegal because `typeof(element)` is `const(T[])` -- one cannot assign to `const`.
So what can we do here? The only options that come to my mind is to either ban such a `const` or cast it away when populating the array, considering `slices_buf` to be uninitialised memory.

Any ideas, anyone?

### PR DESCRIPTION
**Pull request by david-eckardt-sociomantic**
Fix #79 and a few more bugs I found on the way, also clean up the code a bit.
I made it so that the elements of a `const(T[])[]` array (which are of type `const(T[])`) will reside in the slices buffer which by itself is _not_ `const` but should never directly be written to anyway.

### CODE REVIEW

**Comment by gavin-norman-sociomantic** [comment]
If this is a bug fix, it should be based on v2.6.x.

**Comment by gavin-norman-sociomantic** [comment]
>Use `ref` iteration over struct fields

Could you add an explanation of why this change is made, in the commit message?

File: src/ocean/util/serialize/contiguous/Serializer.d [hunk 1]
```diff
@@ -290,7 +290,7 @@ struct Serializer
                         // Recurse into static array elements which contain a
                         // dynamic array.
 
-                        foreach (element; s.tupleof[i])
```
Comment (gavin-norman-sociomantic) [inline src/ocean/util/serialize/contiguous/Serializer.d]: This change (and other similar ones, below) looks unrelated to "Use `ref` iteration over struct fields".

**Comment by gavin-norman-sociomantic** [comment]
>Deserializer: Fix deserialising qualified (i.e. const) arrays
>Serializer: Fix qualified dynamic arrays not detected

Would be nice to have unittests to confirm these fixes.

**Comment by gavin-norman-sociomantic** [comment]
>Unqual whole array at once rather than each element at a time

Could you add an explanation of why this change is made, in the commit message?

File: src/ocean/util/serialize/contiguous/Serializer.d (hunk 1 above)
Comment (david-eckardt-sociomantic) [reply src/ocean/util/serialize/contiguous/Serializer.d]: This commit replaces
```d
foreach (i, T; typeof(s.tupleof)) { /* use s.tupleof[i] to access the i-th field of s */ }
```
with
```d
foreach (i, ref field; s.tupleof) { /* use `field` to access the i-th field of s */ }
```
So it changes both the `foreach` iteration variable to `ref field` and `s.tupleof[i]` to `field` in the loop body.
This particular line here adjusts `s.tupleof[i]` -> `field` that seems to have been missed when the same change had been applied in a previous commit.
Or did you spot a change in this commit that does something different?

**Comment by david-eckardt-sociomantic** [comment]
> Would be nice to have unittests to confirm these fixes.

I added it to the `ocean.util.serialize.contiguous.package_` test.

File: src/ocean/util/serialize/contiguous/Serializer.d (hunk 1 above)
Comment (gavin-norman-sociomantic) [reply src/ocean/util/serialize/contiguous/Serializer.d]: Ah I see. I didn't get the connection between the use of `ref` and the change of `s.tupleof[i]` -> `field`. Maybe just add a bit of explanation in the commit message.

**Comment by gavin-norman-sociomantic** [comment]
>I added it to the ocean.util.serialize.contiguous.package_ test.

In the same commits?

**Comment by david-eckardt-sociomantic** [comment]
> In the same commits?

Ha, no. One commit too late.

**Comment by gavin-norman-sociomantic** [comment]
Maybe put the unittests in the same commits. That'll make it clearer.

**Comment by david-eckardt-sociomantic** [comment]
Updated:
- Addressed @gavin-norman-sociomantic's comments.
- Fixed more bugs, most importantly related to static arrays of dynamic arrays.
- Added support for `const(T[][])` and `const(T[])[n]` (which is the same as `const(T[][n])`).
- Fixed and extended `debug(De/SerializationTrace)` printouts.

I still have to look into `Serializer.resetArrayReferences`, which is not covered by the test and looks `const`-suspicious.

**Comment by gavin-norman-sociomantic** [comment]
On a very quick look, it seems that this PR mixes bug-fixes and refactorings. Sorry -- I know it'll be hassle -- but these should be separated. We shouldn't merge refactorings into v2.6.x.

**Comment by nemanja-boric-sociomantic** [comment]
Maybe it is worth running both D1 and D2 build locally (or on test server where we have RAM) with a profiler and run GetAll on a big channel and see if there's anything that stands out in D2 build. Given that most of the work is done inside the tokyocabinet, maybe it will be obvious what's the difference.

**Comment by david-eckardt-sociomantic** [comment]
Fair enough.

**Comment by david-eckardt-sociomantic** [comment]
Separating bugfixes and refactorings shouldn't be too difficult.

**Comment by gavin-norman-sociomantic** [comment]
Ok great.

File: src/ocean/util/serialize/contiguous/Serializer.d (hunk 1 above)
Comment (david-eckardt-sociomantic) [reply src/ocean/util/serialize/contiguous/Serializer.d]: Ironically this loop has always been broken in two ways: Doing the `foreach` loop is wrong, and in the loop `element` should be passed, not `field`.

**Comment by david-eckardt-sociomantic** [comment]
Updated, reducing the changes to the bug fixes without unrelated refactoring.

File: src/ocean/util/serialize/contiguous/Serializer.d [hunk 2]
```diff
@@ -622,6 +622,7 @@ struct Serializer
                 {
                     // element is a dynamic array
                     data = This.dumpArray(element, data);
+                    *(cast(U*)&element) = null;
```
Comment (mihails-strasuns-sociomantic) [inline src/ocean/util/serialize/contiguous/Serializer.d:641]: Out of curiosity - is there any point in doing so other than simplifying debugging? Deserializer doesn't care if pointers are null or garbage.

File: src/ocean/util/serialize/contiguous/package_.d [hunk 3]
```diff
@@ -696,3 +697,46 @@ unittest
...
+}
+
+unittest
+{
+    void[] buffer;
+
+    ConstS s;
+
+    Serializer.serialize(s, buffer);
+    auto cont_S = Deserializer.deserialize!(ConstS)(buffer);
```
Comment (mihails-strasuns-sociomantic) [inline src/ocean/util/serialize/contiguous/package_.d]: As mentined in other issue, my intention was to not allow this, requiring target struct to be 100% mutable. Exactly because it simplifies (de)serializer code a lot while not being relevant to our typical use cases. What has caused you to pursue such struct support? Original plan was to go with using mutable structs internally and aplying `const` to them as a whole when accepting external params.

**Review by mihails-strasuns-sociomantic — COMMENTED** [review]
Other than `const` concerns I have mentioned, I would really appreciate if every commit that fixes something included matching regression unittest. Serializer code base is rather fragile and convoluted, it would be risky to live even single line change to chance.

File: src/ocean/util/serialize/contiguous/package_.d (hunk 3 above)
Comment (david-eckardt-sociomantic) [reply src/ocean/util/serialize/contiguous/package_.d]: The motivation is to support struct fields containing an array of swarm channels (i.e. strings) where the original channels, passed by the user to the swarm API, can be `immutable(char[])[]`.

Comment (david-eckardt-sociomantic) [reply src/ocean/util/serialize/contiguous/package_.d]: Sorry, I didn't read your comment very well :blush: -- let me check if there was a complication with the original plan.

Comment (mihails-strasuns-sociomantic) [reply src/ocean/util/serialize/contiguous/package_.d]: Please also check with @gavin-norman-sociomantic - we have just had a slack discussion about this and he went to try another approach in dhtproto. It looks like things got a bit of out of control because I expected deserializer to refuse const types and it silently ingored them instead :( Going to see if that alternative approach proves feasible before making decision about serializer.

**Comment by david-eckardt-sociomantic** [comment]
>  I would really appreciate if every commit that fixes something included matching regression unittest.

A regression test is a test that will fail if a fixed bug is re-added again, correct?

**Comment by mihails-strasuns-sociomantic** [comment]
> A regression test is a test that will fail if a fixed bug is re-added again, correct?

Yes. In this context that means that every commit that fixes something should include test that fails without that new fix.

**Comment by david-eckardt-sociomantic** [comment]
There are still several dynamic array detections which incorrectly do not unqualify the input type so they should detecting `const(T[])` as a dynamic array, but surprisingly they succeed. This is my surprise:
```d
alias const(char[]) T;
static if (is(T U == U[]))
    static assert(is(T == U[])); // fails -- why is it true in the static if?
```
The [D2 specification](http://dlang.org/spec/expression.html#IsExpression) says
> The condition is satisfied if _Type_ [i.e. `T`] is semantically correct and is the same as _TypeSpecialization_ [i.e. `U[]`].

In the example the condition is satisfied but they are not the same as the `static assert` confirms. Is this a compiler bug? I couldn't find an issue on https://issues.dlang.org/ so far.

If it was really a compiler bug it would hide bugs in the `Serializer` code.

**Comment by david-eckardt-sociomantic** [comment]
DMD bug reported: https://issues.dlang.org/show_bug.cgi?id=17353

**Comment by david-eckardt-sociomantic** [comment]
Updated:
- Regression tests
- Added `Unqual` to dynamic array type checks including those that would work by accident due to DMD bug #17353.

File: src/ocean/util/serialize/contiguous/Serializer.d [hunk 4]
```diff
@@ -622,6 +622,7 @@ struct Serializer
                 {
                     // element is a dynamic array
                     data = This.dumpArray(element, data);
+                    *(cast(T*)&element) = null;
```
Comment (mihails-strasuns-sociomantic) [inline src/ocean/util/serialize/contiguous/Serializer.d]: This is going to be a problem with https://github.com/sociomantic-tsunami/ocean/pull/88 though - or do we have a way to reset all pointers to null in-place?

**Comment by mihails-strasuns-sociomantic** [comment]
@david-eckardt-sociomantic I see that it still has changes to support `const` in deserializer - could you please move them to separate PR so that non-controversial serializer fixes can be merged ASAP?

**Comment by david-eckardt-sociomantic** [comment]
Updated, now rejecting type qualifiers in `Deserializer`. This changes only one commit, `De/Serializer: Reject and support const(T[]) and const(T[])[n] fields, resp`.

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

File: src/ocean/util/serialize/contiguous/Deserializer.d [hunk 5]
```diff
@@ -1089,6 +1093,20 @@ struct Deserializer
...
+    /**************************************************************************
+
+        `static assert`s that `T` has no qualifier.
+
+     **************************************************************************/
+
+    template RejectQualifier ( T )
+    {
+        version (D_Version2)
+            static assert(is(T == typeof(mixin("cast()T.init"))),
```
Comment (mihails-strasuns-sociomantic) [inline src/ocean/util/serialize/contiguous/Deserializer.d]: As this is bug fix release, please make it `pragma` for now!

**Review by mihails-strasuns-sociomantic — CHANGES_REQUESTED** [review]
One last request :)

**Review by mihails-strasuns-sociomantic — APPROVED** [review]
