### PR TITLE
Decode the base64 with the missing padding

### LINKED ISSUE #155: Base64 decoding of unpadded data leads to incomplete decoded data.
Extending the following unit test to check for the decoding of padded data shows that the decoding is broken.

https://github.com/sociomantic-tsunami/ocean/blob/v2.x.x/src/ocean/util/encode/Base64.d#L514
```
// Encode without padding
unittest
{
    istring str = "Hello, how are you today?";
    Const!(ubyte)[] payload = cast(Const!(ubyte)[]) str;
    cstring result = encode(payload, false);
    test!("==")(result, "SGVsbG8sIGhvdyBhcmUgeW91IHRvZGF5Pw");

  
    auto decoded = cast(cstring)decode(result);
    test!("==")(decoded, str);
}
```
results in 
```
./src/ocean/util/encode/Base64.d:521: test error: expression 'Hello, how are you today == Hello, how are you today?' evaluates to false
```

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**
This makes base64 work when there not all padding bytes needed are in
the input string. It decodes as many whole non-padded quartets as it
can, and then it tries to decode the last remaining bytes into a pair,
or a single character.

Fixes #155

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
@scott-gibson-sociomantic could you try this in your use case?

**Comment by scott-gibson-sociomantic** [comment]
Confirming that changes are working with my use case.

File: src/ocean/util/encode/Base64.d [hunk 1]
```diff
@@ -503,10 +508,38 @@ unittest
     // decodeTest
     {
         ubyte[1024] decoded;
-        ubyte[] result = decode("SGVsbG8sIGhvdyBhcmUgeW91IHRvZGF5Pw==", decoded);
+        Const!(ubyte)[] result = decode("SGVsbG8sIGhvdyBhcmUgeW91IHRvZGF5Pw==", decoded);
```
Comment (mathias-lang-sociomantic) [inline src/ocean/util/encode/Base64.d]: Why this change ?

File: src/ocean/util/encode/Base64.d [hunk 2]
```diff
@@ -446,12 +446,17 @@ body
...
+            // Fill the missing paddings if needed
+            base64Quad[padded.length .. $] = BASE64_PAD;
+
+            foreach(i, char piece; padded)
             {
                 ubyte next = table[piece];
                 if (next || piece == 'A')
                     *quadPtr++ = next;
-                if (quadPtr is endPtr)
+                if (i == padded.length - 1)
```
Comment (mathias-lang-sociomantic) [inline src/ocean/util/encode/Base64.d:470]: Can `padded.length` ever be `0` ?

Comment (nemanja-boric-sociomantic) [reply src/ocean/util/encode/Base64.d:470]: No, that would require that `paddedPos` is zero, so it would not enter this branch. Additionally, the `foreach` wouldn't iterate over `padded`.

File: src/ocean/util/encode/Base64.d (hunk 1 above)
Comment (nemanja-boric-sociomantic) [reply src/ocean/util/encode/Base64.d]: because of the reassigning it here: https://github.com/sociomantic-tsunami/ocean/pull/156/files/7ba30bf6d7030f4220b2eeaeaf443ad324444622#diff-183a2b58e80d01cce23dd21bd51c86ceR521

Not terribly important, though, I can try to please you - I was just fixing the d2 failure.

File: src/ocean/util/encode/Base64.d (hunk 2 above)
Comment (mathias-lang-sociomantic) [reply src/ocean/util/encode/Base64.d:470]: > Additionally, the foreach wouldn't iterate over padded.

:man_facepalming:

File: src/ocean/util/encode/Base64.d (hunk 1 above)
Comment (mathias-lang-sociomantic) [reply src/ocean/util/encode/Base64.d]: I'd just like to have a test that ensure we're getting a mutable buffer. Would it be possible to use another variable instead ? Actually it could be its own unittest block

File: src/ocean/util/encode/Base64.d [hunk 3]
```diff
@@ -503,10 +508,38 @@ unittest
...
         result = decode("SGVsbG8sIGhvdyBhcmUgeW91IHRvZGF5Pw==");
         test!("==")(result, payload);
+        result = decode("SGVsbG8sIGhvdyBhcmUgeW91IHRvZGF5Pw=");
+        test!("==")(result, payload);
+        result = decode("SGVsbG8sIGhvdyBhcmUgeW91IHRvZGF5Pw");
+        test!("==")(result, payload);
+
+        // try the string with the single `=` padding, and without it
+        result = cast(Const!(ubyte)[])"any carnal pleasure.";
+        test!("==")(cast(char[])result, cast(char[])decode("YW55IGNhcm5hbCBwbGVhc3VyZS4="));
```
Comment (mathias-lang-sociomantic) [inline src/ocean/util/encode/Base64.d]: No casting of `istring` to `mstring` please :(

File: src/ocean/util/encode/Base64.d (hunk 1 above)
Comment (nemanja-boric-sociomantic) [reply src/ocean/util/encode/Base64.d]: Sure, good point.

File: src/ocean/util/encode/Base64.d (hunk 3 above)
Comment (nemanja-boric-sociomantic) [reply src/ocean/util/encode/Base64.d]: Yup, it was the debuging aid, removed.

**Comment by nemanja-boric-sociomantic** [comment]
Updated with the comments from @mathias-lang-sociomantic

**Review by mathias-lang-sociomantic — APPROVED** [review]

File: src/ocean/util/encode/Base64.d [hunk 4]
```diff
@@ -507,6 +512,37 @@ unittest
...
+    {
+        // try the string with the single `=` padding, and without it
+        auto result = cast(Const!(ubyte)[])"any carnal pleasure.";
+        test!("==")(result, decode("YW55IGNhcm5hbCBwbGVhc3VyZS4="));
+        test!("==")(result, decode("YW55IGNhcm5hbCBwbGVhc3VyZS4"));
+    }
+
+    // short decode test
+    {
+        ubyte[1024] decoded;
```
Comment (david-eckardt-sociomantic) [inline src/ocean/util/encode/Base64.d]: - Unused: Should it be passed to `decode`?
- What is the reason for this length, could it as well be `result.length`?

**Comment by david-eckardt-sociomantic** [comment]
It would be good to document this extension. Just supporting missing padding bytes makes me wonder:
- What is the point of padding bytes if they can be omitted?
- Can they always be omitted, or are there cases where some or all padding bytes are required?
- Given a Base-64 string that normally has padding bytes, can removing one or all padding bytes change the decoder output?

File: src/ocean/util/encode/Base64.d (hunk 4 above)
Comment (nemanja-boric-sociomantic) [reply src/ocean/util/encode/Base64.d]: Ah, its a copy/paste error. I will remove. `decode` has overflow which will allocate its own buffer, I think that's fine for this unittest.

**Comment by nemanja-boric-sociomantic** [comment]
> What is the point of padding bytes if they can be omitted?

The reason where you need padding bytes is when you need concatenate multiple base64 strings. If there are no padding bytes at the end of the first base64 string, decoder will chop off missing bytes from the second string, and interpret them as a part of the first string.

> Can they always be omitted, or are there cases where some or all padding bytes are required?

See above.


> Given a Base-64 string that normally has padding bytes, can removing one or all padding bytes change the decoder output?

In a case of a single base64 string (not series of it), removing one or all padding bytes can't change the decoder output. This is the case here, as our decoder doesn't support decoding multiple byte64 sequences. I'm investigating if that's a bug.

In any case, this is very good point, I will improve the documentation.

**Comment by nemanja-boric-sociomantic** [comment]
> I'm investigating if that's a bug.

This seems to be done by design. I'll submit another PR based on v2.x.x which adds support for this.

**Comment by nemanja-boric-sociomantic** [comment]
Updated with the removed `ubyte` array and some more documentation on the padding.

**Comment by nemanja-boric-sociomantic** [comment]
Feature for decoding multiple strings: #158

File: src/ocean/util/encode/Base64.d [hunk 5]
```diff
@@ -317,6 +317,12 @@ body
     unique. This allows the use of decode tables with alternatives for certain
     characters.
 
+    Since the padding is required only between multiple base64 strings (for the
```
Comment (gavin-norman-sociomantic) [inline src/ocean/util/encode/Base64.d:320]: Unmatched (

File: src/ocean/util/encode/Base64.d [hunk 6]
```diff
@@ -358,6 +364,11 @@ body
...
```
Comment (gavin-norman-sociomantic) [inline src/ocean/util/encode/Base64.d:367]: Unmatched (

File: src/ocean/util/encode/Base64.d [hunk 7]
```diff
@@ -507,6 +523,35 @@ unittest
...
+    // short decode test
+    {
+        auto result = cast(Const!(ubyte)[])"M";
+
+        test!("==")(result, decode("TQ"));
+        test!("==")(result, decode("TQ="));
+        test!("==")(result, decode("TQ=="));
+    }
+    // ditto
+    {
```
Comment (gavin-norman-sociomantic) [inline src/ocean/util/encode/Base64.d]: What's this test checking that the preceding one ("short decode test") doesn't?

Comment (nemanja-boric-sociomantic) [reply src/ocean/util/encode/Base64.d]: It tests the case where you get less than four characters, and +/- padding. I'll set the documentation straight.

Comment (nemanja-boric-sociomantic) [reply src/ocean/util/encode/Base64.d]: ah, actually it was single `=` and double `==` required for padding.

**Comment by nemanja-boric-sociomantic** [comment]
Updated.

**Review by gavin-norman-sociomantic — APPROVED** [review]
